apiVersion: apps/v1

kind: Deployment 

metadata:
  name: k8s-app
  labels:
    app: k8s-app  

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: k8s-app 

  template: 
    metadata:
      labels:
        app: k8s-app 

    spec: 
      containers:
        - name:  k8s-app 
          image: 592587463331.dkr.ecr.eu-north-1.amazonaws.com/k8s-app:v1
          ports:
          - containerPort: 5000 