apiVersion: v1

kind: Service 

metadata:   
  name: k8s-app

spec: 
  type: {{ .Values.service.type}}

  selector:
    app: k8s-app
  
  ports:
    - protocol: {{ .Values.service.protocol}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}